package com.hk.xia.mybatisplus.generator.code.pojo;

public class Employer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.bId
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employer.bName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    private String bname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.bId
     *
     * @return the value of employer.bId
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.bId
     *
     * @param bid the value for employer.bId
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employer.bName
     *
     * @return the value of employer.bName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employer.bName
     *
     * @param bname the value for employer.bName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public void setBname(String bname) {
        this.bname = bname;
    }
}