package com.hk.xia.mybatisplus.generator.code.pojo;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.eId
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.eName
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.stageName
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    private String stagename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.eId
     *
     * @return the value of employee.eId
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.eId
     *
     * @param eid the value for employee.eId
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.eName
     *
     * @return the value of employee.eName
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.eName
     *
     * @param ename the value for employee.eName
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.stageName
     *
     * @return the value of employee.stageName
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    public String getStagename() {
        return stagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.stageName
     *
     * @param stagename the value for employee.stageName
     *
     * @mbg.generated Fri Aug 02 10:14:30 CST 2019
     */
    public void setStagename(String stagename) {
        this.stagename = stagename;
    }
}