package com.hk.xia.mybatisplus.generator.code.pojo;

public class HkEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hk_employee.hkId
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    private Integer hkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hk_employee.hkName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    private String hkname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hk_employee.hkStageName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    private String hkstagename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_employee.hkId
     *
     * @return the value of hk_employee.hkId
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public Integer getHkid() {
        return hkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_employee.hkId
     *
     * @param hkid the value for hk_employee.hkId
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public void setHkid(Integer hkid) {
        this.hkid = hkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_employee.hkName
     *
     * @return the value of hk_employee.hkName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public String getHkname() {
        return hkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_employee.hkName
     *
     * @param hkname the value for hk_employee.hkName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public void setHkname(String hkname) {
        this.hkname = hkname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hk_employee.hkStageName
     *
     * @return the value of hk_employee.hkStageName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public String getHkstagename() {
        return hkstagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hk_employee.hkStageName
     *
     * @param hkstagename the value for hk_employee.hkStageName
     *
     * @mbg.generated Fri Aug 02 11:38:38 CST 2019
     */
    public void setHkstagename(String hkstagename) {
        this.hkstagename = hkstagename;
    }
}